@tool
extends RefCounted
class_name NoteUILibraryGenerator

const default_fragments: Array[NoteAppLibraryEntry] = [
	preload("uid://c2iasdqkl31b0"),
	preload("uid://bg5kigat0i7qn"),
	preload("uid://ckx1u4tcscw5a")
]

var fragments: Array[NoteAppLibraryEntry] = []

func _validate(frag: NoteAppLibraryEntry) -> bool:
	if frag.frag_scene == null or frag.frag_script == null:
		return false
	return true

func _get_private_for(frag: NoteAppLibraryEntry, root_class_name: String) -> String:
	var frag_class_name = frag.frag_name.to_pascal_case()
	var private_ref = "%s._private.%s" % [root_class_name, frag_class_name]
	var bit = """	class %s extends RefCounted:
		var _injected_shell_node: NoteAppShell.ShellNode\n""" % [frag_class_name]
	if frag.can_contain_children:
		bit += """		func with_children(children: Array) -> %s:
			_injected_shell_node.with_children(children)
			return self\n""" % [private_ref]

	## ADD PROP METHODS
	for p in frag.props:
		bit += """		func with_%s(%s) -> %s:
			_injected_shell_node.props[&\"%s\"] = %s
			return self\n""" % [p.to_snake_case(),p.to_snake_case(),private_ref,p,p.to_snake_case()]
	
	## ADD EVENT METHOD
	for e in frag.events:
		bit += """		func on_%s(event_method: Callable) -> %s:
			_injected_shell_node.on(&\"%s\", event_method)
			return self\n""" % [e.to_snake_case(),private_ref,e]
	
	## ADD FLAG METHODS
	for f in frag.flags:
		bit += """		func as_%s(is_enabled: bool = true) -> %s:
			if is_enabled:
				_injected_shell_node.props[&\"%s\"] = true
			return self\n""" % [f.to_snake_case(),private_ref,f]

	return bit
func _get_main_for(frag: NoteAppLibraryEntry, root_class_name: String) -> String:
	var frag_class_name = frag.frag_name.to_pascal_case()
	var frag_uid = ResourceUID.path_to_uid(frag.frag_scene.resource_path)
	var bit = """
## %s
@abstract
class %s extends Object:
	static func make() -> _private.%s:
		var new_instance = _private.%s.new()
		new_instance._injected_shell_node = NoteAppShell.currently_running_shell.with(\"%s\")
		return new_instance\n""" % [
		frag.frag_description if !frag.frag_description.is_empty() else "A NoteAppShell component.",
		frag_class_name,
		frag_class_name,
		frag_class_name,
		frag_uid
	]
	
	return bit
func run(settings: NoteDeveloperSettings):
	if !Engine.is_editor_hint(): return
	if settings.include_note_fragments:
		fragments.append_array(default_fragments)
	fragments.append_array(settings.container_fragments)
	fragments.append_array(settings.control_fragments)
	fragments = fragments.filter(_validate)
	
	print(str(fragments))
	if settings.disable_library_generation or fragments.is_empty():
		var libfile = FileAccess.open("res://addons/note/_library.gd",FileAccess.WRITE)
		if libfile == null:
			push_error("Failed to generate note VMU library: %s" % FileAccess.get_open_error())
		libfile.store_string("""extends Object
## Disabled generation (or empty fragments array). Keep file around, no need to care about it.
""")
		libfile.close()
		return
	
	var private_body: String = ""
	for f in fragments:
		if f == null: continue
		private_body += "%s" % _get_private_for(f, settings.generated_library_name)
	
	var main_body: String = ""
	for f in fragments:
		if f == null: continue
		main_body += "%s" % _get_main_for(f, settings.generated_library_name)
	var file = """@abstract
extends Object
class_name %s
## AUTOGENERATED do not modify [br]
## - A listing file with all of your VMU components.

@abstract
class _private extends Object:
%s
%s\n""" % [settings.generated_library_name, private_body, main_body]
	
	var scr: GDScript = load("res://addons/note/_library.gd")
	scr.source_code = file
	scr.reload()
	ResourceSaver.save(scr)
	print("Note UI Library: %s script fully regenerated" % settings.generated_library_name)
