@tool
extends RefCounted
class_name NoteUILibraryGenerator

const default_fragments: Array[NoteAppLibraryEntry] = [
	
]

var fragments: Array[NoteAppLibraryEntry] = []

func _get_private_for(frag: NoteAppLibraryEntry, root_class_name: String) -> String:
	var frag_class_name = frag.frag_name.to_pascal_case()
	var private_ref = "%s._private.%s" % [root_class_name, frag_class_name]
	var bit = """class %s extends RefCounted:
		var _injected_shell_node: NoteAppShell.ShellNode
""" % [frag_class_name]
	if frag.can_contain_children:
		bit += """		func with_children(children: Array) -> %s:
			return self
""" % [private_ref]
	for p in frag.props:
		bit += """		func with_%s(%s) -> %s:
			return self
""" % [p.to_snake_case(),p.to_snake_case(),private_ref]
	return bit
func _get_main_for(frag: NoteAppLibraryEntry, root_class_name: String) -> String:
	var frag_class_name = frag.frag_name.to_pascal_case()
	
	var bit = """
## %s
@abstract
class %s extends Object:
	static func make() -> _private.%s:
		var new_instance = _private.%s.new()
		new_instance._injected_shell_node = new_instance._shell.with(\"%s\")
		return new_instance
""" % [
		frag.frag_description if !frag.frag_description.is_empty() else "A NoteAppShell component.",
		frag_class_name,
		frag_class_name,
		frag_class_name,
		frag.frag_scene.resource_path
	]
	return bit
func run(settings: NoteDeveloperSettings):
	if !Engine.is_editor_hint(): return
	if settings.disable_library_generation:
		var libfile = FileAccess.open("res://addons/note/_library.gd",FileAccess.WRITE)
		if libfile == null:
			push_error("Failed to generate note VMU library: %s" % FileAccess.get_open_error())
		libfile.store_string("""extends Object
## Disabled generation. Keep file around, no need to care about it.
""")
		libfile.close()
		return
	if settings.include_note_fragments:
		fragments.append_array(default_fragments)
	fragments.append_array(settings.container_fragments)
	fragments.append_array(settings.control_fragments)
	
	var private_body: String = ""
	for f in fragments:
		if f == null: continue
		private_body += "%s\n" % _get_private_for(f, settings.generated_library_name)
	
	var main_body: String = ""
	for f in fragments:
		if f == null: continue
		main_body += "%s\n" % _get_main_for(f, settings.generated_library_name)
	var file = """@abstract
extends Object
class_name %s
## AUTOGENERATED do not modify
## A listing file with all of your fragment components.

@abstract
class _private extends Object:
	%s

%s
""" % [settings.generated_library_name, private_body, main_body]
	
	var libfile = FileAccess.open("res://addons/note/_library.gd",FileAccess.WRITE)
	if libfile == null:
		push_error("Failed to generate note VMU library: %s" % FileAccess.get_open_error())
	libfile.store_string(file)
	libfile.close()
	print("Note UI Library: %s script fully regenerated" % settings.generated_library_name)
